### ISSUE TITLE
Setup Events and Event doctypes

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/Umbraco-v8-Community-Website-StarterKit#36]
Part of the site is an events bits...so we need the doctypes setup

**Comment by prgriffithsdev** [comment]
I can take this next if you like Tim, would you like me to follow a similar approach to the articles? Please let me know any other ideas you have for events. thanks

**Comment by TimGeyssens** [comment]
Yes would be awesome...just need to figure out the event properties...start date/end date/location(Google maps) ?

**Comment by prgriffithsdev** [comment]
Okay, ill start thinking about what we need on the doctype. We can always add remove so ill focus on getting something committed and build from there. I will do it without a controller, to begin with, but if we require any additional logic we can refactor and create an EventsController. I'm out the kids at the moment so ill make a start later

**Comment by TimGeyssens** [comment]
Nice, yes the controller #39  is a seperate Task :)

**Comment by deanleigh** [comment]
I don't know if this is useful but here is an example of how I created events for Colchester Digital.

We have an events listing page here:
[https://colchesterdigital.org.uk/events/](url)

We have events pages like this:
[https://colchesterdigital.org.uk/events/developer-lessons-from-large-to-small-projects/](url)

The Event Page allows several Nested Content Blocks such as Sponsors but the main Nest Content Block is the Schedule Builder.
Schedule Builder is a Nested Content block that in turn nests other Nested Content Blocks such as Talks and Breaks

So essentially Events are a Group of Talk DocTypes

Talks in turn make use of Speaker DocTypes and some talks have many speakers and of course many speakers do multiple talks e.g. you can see Ashleigh's other talks on her Speaker page:
[https://colchesterdigital.org.uk/speakers/ashleigh-simonelli/](url)

I hope this makes sense

**Comment by TimGeyssens** [comment]
@deanleigh nice for sharing :) 

@prgriffithsdev yes ace, I would love to have some facetted search on events...

**Comment by prgriffithsdev** [comment]
Hey both, thanks for the updates. @deanleigh, I haven't made a start yet so if this is something you want to pick up I can take a look at attempting something else? If you already have a solid solution then it might make sense for you to thrash it out. 

Let me know :)

**Comment by TimGeyssens** [comment]
I understand the nested content approach... but for the overview/landing page I would just use a rather simple output... that can be filtered with a nice facetted search solution... for the event details... key is start/end date , location , details ... not sure what else migth be required and make sense?

**Comment by TimGeyssens** [comment]
These might give some inspiration:

https://demo1.imithemes.com/html/born-to-give/events.html
https://demo1.imithemes.com/html/born-to-give/events-grid.html
https://landtemplates.com/previews/events-list.html
http://templates.theemon.com/?theme=charity-html

**Comment by prgriffithsdev** [comment]
I can add in the simple doc types\properties and build up some test pages a bit like articles. Once checked in, this can be worked on\refactored as necessary. Iv not done a lot with search so ill take a look at the links you provided and see if i can build a facet. Maybe some new issues and link to this. 

Ill get some event stuff checked in tonight, at least its a start

**Comment by TimGeyssens** [comment]
Sounds good!

**Comment by TimGeyssens** [comment]
FIxed by @prgriffithsdev in #67
