### ISSUE TITLE
Setup Faq Area and Faq doctypes

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/Umbraco-v8-Community-Website-StarterKit#43]
For Faq Area a normal doctype

For Faq an element type

Then a nested content datatype for Faqs

**Comment by Mantus667** [comment]
I would love to jump on this one if not already taken :)

**Comment by TimGeyssens** [comment]
Do it!

**Comment by TimGeyssens** [comment]
Fixed with pr #64
