### ISSUE TITLE
Bring tabs in the mix

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/Umbraco-v8-Community-Website-StarterKit#50]
Install Matryoshka https://our.umbraco.com/packages/backoffice-extensions/matryoshka-tabs-for-umbraco-8/ (with nuget)

**Comment by prgriffithsdev** [comment]
Hey Tim, ill add this package so I can implement and get a feel for the process to check-in and create a PR. I have the repo forked, cloned, running locally, and imported in uSync. Let me know the instructions and ill get this added - am i able to assign this to myself ?

**Comment by TimGeyssens** [comment]
hey @prgriffithsdev awesome! Just comming and push to the main branch of your fork... then you can create pr with the github ui. 

I'll check if I can open up the assignees bit... for now maybe just leave a comment... that you are handling this 👍

**Comment by prgriffithsdev** [comment]
Cool, that's the PR all done and hopefully, it's correct, I've not contributed before :)

**Comment by TimGeyssens** [comment]
It is perfect :) thanks! And I think you just earned the Umbraco swag :)

**Comment by prgriffithsdev** [comment]
Thanks, Tim, ill look through the issue list and see what else I can do. #onaroll
