### ISSUE TITLE
Look at how we can get some content at startup... for the new folks forking and running the project

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/Umbraco-v8-Community-Website-StarterKit#52]
Now uSync handles the rest... but also some intial content would be ace

**Comment by CarlSargunar** [comment]
I actually had this as a package idea - a Lorem Ipsum content generator for initially setting up a site. It's a pain in the ass task and it would also perhaps make me get on and finish my package for it too

**Comment by TimGeyssens** [comment]
sounds good!

**Comment by TimGeyssens** [comment]
Maybe if we ask nice Kevin can give is a dev license for uSync content edition... that just works locally + maybe  xip.io domains...

**Comment by skttl** [comment]
uSync Content Edition doesn't require a license

**Comment by TimGeyssens** [comment]
@skttl ... well I be damned... thanks :)

**Comment by KevinJump** [comment]
I had a ebook -> content generator somewhere - so you could push a load of ebook stuff into umbraco - used it mainly for load testing.

**Comment by KevinJump** [comment]
The localgov starter kit, used a slightly modified bit of code to call uSync.Core - https://github.com/KevinJump/LocalGovStarterKit/blob/v6-main/Src/Jumoo.StarterKit.Installer/ContentImporter.cs 

and it also had some code to importe the LGNL (UK Localgoverment navigation list - which you can get as an XML feed) 

it did it from a dashboard after you installed it. https://github.com/KevinJump/LocalGovStarterKit/blob/v6-main/Src/LGStarterKit.Site/App_Plugins/lgsk/StarterKitInstall.ascx

**Comment by TimGeyssens** [comment]
Ok uSync content edition has been added :)

**Comment by TimGeyssens** [comment]
For now I'll close this one.... if we need more advance stuff like Kevin mentions we can add new issue

**Comment by CarlSargunar** [comment]
Sounds good - thanks for the info @KevinJump

**Comment by CarlSargunar** [comment]
It might be an idea to add some info to the readme for anyone less familiar with uSync, and also generally for the initial website setup so we can get to a common starting point with a database containing content AND structure sooner rather than later

**Comment by TimGeyssens** [comment]
@CarlSargunar good idea, feel free to update the readme :)
