### ISSUE TITLE
Setup navs on website doctype

### ISSUE THREAD

**Issue by TimGeyssens** [TimGeyssens/Umbraco-v8-Community-Website-StarterKit#55]
using meganav! #54

**Comment by TimGeyssens** [comment]
Main nav -> meganav
Footer nav -> meganav

**Comment by AaronSadlerUK** [comment]
I'll work on this and make a PR soon.
Feel free to assign this issue to me :)

**Comment by TimGeyssens** [comment]
Niiiice!

**Comment by TimGeyssens** [comment]
Fixed with pr #58
